[build]
  base = "/"
  publish = "dist/"
  command  = "npm run build"
  functions = "netlify/functions/"
  edge_functions = "netlify/edge_functions/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200